name: eShop Pull Request Validation

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'src/ClientApp/**'
      - 'test/ClientApp.UnitTests/**'
      - '.github/workflows/pr-validation-maui.yml'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'src/ClientApp/**'
      - 'test/ClientApp.UnitTests/**'
      - '.github/workflows/pr-validation-maui.yml'

jobs:  
  test:
    runs-on: WoArm-runner
    steps:
      - name: Print Windows Version
        run: |
          echo "::set-env name=ANSI_RESET::\x1b[0m"
          echo "::set-env name=ANSI_GREEN::\x1b[1;32m"          
          echo "${{ env.ANSI_GREEN }}Windows Version:${{ env.ANSI_RESET }} ${{ runner.os }}"
          echo "${{ env.ANSI_GREEN }}Architecture:${{ env.ANSI_RESET }} ${{ runner.arch }}"      
      - uses: actions/checkout@v4
      - name: Setup .NET (global.json)
        uses: actions/setup-dotnet@v3
      - name: Update Workloads
        run: dotnet workload update
      - name: Install Workloads
        run: dotnet workload install aspire
      - name: Build 
        run: dotnet build eShop.Web.slnf
