name: eShop Pull Request Validation

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'src/ClientApp/**'
      - 'test/ClientApp.UnitTests/**'
      - '.github/workflows/pr-validation-maui.yml'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'src/ClientApp/**'
      - 'test/ClientApp.UnitTests/**'
      - '.github/workflows/pr-validation-maui.yml'

jobs:  
  buildandtest:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Display Runner config
        run: echo "Runner OS: $env:RUNNER_OS."
        run: echo "Runner Arch: $env:RUNNER_ARCH."
      - name: Setup .NET (global.json)
        uses: actions/setup-dotnet@v3
      - name: Update Workloads
        run: dotnet workload update
      - name: Install Workloads
        run: dotnet workload install aspire
      - name: Build 
        run: dotnet build eShop.Web.slnf
